# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('courier_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('courier_onfleet_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Onfleet ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('phone', models.CharField(help_text='Example: +34625188877', max_length=15, verbose_name='Phone')),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Courier',
                'verbose_name_plural': 'Couriers',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('team_onfleet_id', models.CharField(blank=True, max_length=500, null=True, verbose_name='Onfleet ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='courier',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='couriers.Team'),
        ),
    ]
