# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 13:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_auto_20170327_1501'),
        ('payment', '0002_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='eur', max_length=20, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_delivery',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='payment_delivery', to='deliveries.Delivery'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
