# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency')),
                ('symbol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Symbol')),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Iso Code')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'verbose_name': 'Currency',
            },
        ),
    ]
