version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    command: /gunicorn.sh
    env_file: .env

  nginx:
    build: ./compose/nginx
    depends_on:
      - django

    ports:
      - "0.0.0.0:80:80"
