# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, default=1, max_length=300, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
