# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20170518_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Email'),
        ),
    ]
