# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='Address')),
                ('zipcode', models.CharField(blank=True, max_length=300, null=True, verbose_name='Zipcode')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('address_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Address_City', to='location.City')),
            ],
            options={
                'verbose_name': ('Address',),
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='AddressBook',
            fields=[
                ('address_book_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('addresses', models.ManyToManyField(to='address.Address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressbook_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': ('AddressBook',),
                'verbose_name_plural': 'AddressesBook',
            },
        ),
    ]
