# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineOrderCourier',
            fields=[
                ('line_order_courier_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': ('Line Order Courier',),
                'verbose_name_plural': 'Lines Order Courier',
            },
        ),
        migrations.CreateModel(
            name='LineOrderUser',
            fields=[
                ('line_order_user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': ('Line Order User',),
                'verbose_name_plural': 'Lines Order User',
            },
        ),
        migrations.CreateModel(
            name='OrderCourier',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Reference')),
                ('nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIF')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='ZipCode')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('snabb_nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_NIF')),
                ('snabb_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Name')),
                ('snabb_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Company')),
                ('snabb_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Phone')),
                ('snabb_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Address')),
                ('snabb_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Region')),
                ('snabb_zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_ZipCode')),
                ('snabb_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_Country')),
                ('snabb_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_City')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': ('Order Courier',),
                'verbose_name_plural': 'Orders Courier',
            },
        ),
        migrations.CreateModel(
            name='OrderUser',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_reference', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Reference')),
                ('nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIF')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='ZipCode')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('snabb_nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_NIF')),
                ('snabb_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Name')),
                ('snabb_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Company')),
                ('snabb_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Phone')),
                ('snabb_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Address')),
                ('snabb_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Region')),
                ('snabb_zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_ZipCode')),
                ('snabb_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_Country')),
                ('snabb_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_City')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': ('Order User',),
                'verbose_name_plural': 'Orders User',
            },
        ),
    ]
