# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_auto_20170327_1501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('couriers', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineReceiptCourier',
            fields=[
                ('line_receipt_courier_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': ('Line Receipt Courier',),
                'verbose_name_plural': 'Lines Receipt Courier',
            },
        ),
        migrations.CreateModel(
            name='LineReceiptUser',
            fields=[
                ('line_receipt_user_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Task')),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': ('Line Receipt User',),
                'verbose_name_plural': 'Lines Receipt User',
            },
        ),
        migrations.CreateModel(
            name='ReceiptCourier',
            fields=[
                ('receipt_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('receipt_reference', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Reference')),
                ('nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIF')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='ZipCode')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('snabb_nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_NIF')),
                ('snabb_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Name')),
                ('snabb_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Company')),
                ('snabb_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Phone')),
                ('snabb_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Address')),
                ('snabb_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Region')),
                ('snabb_zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_ZipCode')),
                ('snabb_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_Country')),
                ('snabb_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_City')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bill_Courier', to='couriers.Courier', verbose_name='Courier')),
                ('receipt_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Receipt_Courier_Delivery', to='deliveries.Delivery', verbose_name='Delivery')),
            ],
            options={
                'verbose_name': ('Receipt Courier',),
                'verbose_name_plural': 'Receipts Courier',
            },
        ),
        migrations.CreateModel(
            name='ReceiptUser',
            fields=[
                ('receipt_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('receipt_reference', models.CharField(editable=False, max_length=500, unique=True, verbose_name='Reference')),
                ('nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='NIF')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Company')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='ZipCode')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('snabb_nif', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_NIF')),
                ('snabb_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Name')),
                ('snabb_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Company')),
                ('snabb_phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Phone')),
                ('snabb_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Address')),
                ('snabb_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='SNABB_Region')),
                ('snabb_zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='SNABB_ZipCode')),
                ('snabb_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_Country')),
                ('snabb_city', models.CharField(blank=True, max_length=50, null=True, verbose_name='SNABB_City')),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('receipt_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Receipt_User_Delivery', to='deliveries.Delivery', verbose_name='Delivery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Bill_User', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': ('Receipt User',),
                'verbose_name_plural': 'Receipts User',
            },
        ),
        migrations.RemoveField(
            model_name='lineordercourier',
            name='order_courier',
        ),
        migrations.RemoveField(
            model_name='lineorderuser',
            name='order_user',
        ),
        migrations.RemoveField(
            model_name='ordercourier',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='ordercourier',
            name='order_delivery',
        ),
        migrations.RemoveField(
            model_name='orderuser',
            name='order_delivery',
        ),
        migrations.RemoveField(
            model_name='orderuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='LineOrderCourier',
        ),
        migrations.DeleteModel(
            name='LineOrderUser',
        ),
        migrations.DeleteModel(
            name='OrderCourier',
        ),
        migrations.DeleteModel(
            name='OrderUser',
        ),
        migrations.AddField(
            model_name='linereceiptuser',
            name='receipt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceiptUser', to='billing.ReceiptUser', verbose_name='ReceiptUser'),
        ),
        migrations.AddField(
            model_name='linereceiptcourier',
            name='receipt_courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ReceiptCourier', to='billing.ReceiptCourier', verbose_name='ReceiptCourier'),
        ),
    ]
