# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='City Name')),
                ('google_short_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Google City Name')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Name Country')),
                ('iso_code', models.CharField(blank=True, max_length=3, null=True, verbose_name='Iso Code')),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('country_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_currency', to='currency.Currency')),
            ],
            options={
                'verbose_name': ('Country',),
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, verbose_name='Region')),
                ('google_short_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Google Region Name')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('region_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_country', to='location.Country')),
            ],
            options={
                'verbose_name': ('Region',),
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('zipcode_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=300, verbose_name='Code')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('zipcode_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Zipcode_city', to='location.City')),
            ],
            options={
                'verbose_name': 'Zipcode',
                'verbose_name_plural': 'Zipcodes',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='city_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_region', to='location.Region'),
        ),
        migrations.AlterUniqueTogether(
            name='zipcode',
            unique_together=set([('code', 'zipcode_city')]),
        ),
    ]
