# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='price_canceled',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
    ]
