# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quote_id', models.CharField(blank=True, default='', max_length=100)),
                ('currency_code', models.CharField(blank=True, default='SEK', max_length=100)),
                ('tracking_url', models.TextField(default='')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default='0.0')),
                ('longitude', models.FloatField(default='0.0')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quote_id', models.CharField(max_length=20, unique=True)),
                ('currency_code', models.CharField(blank=True, default='SEK', max_length=100)),
                ('pickup_eta', models.IntegerField(default=0)),
                ('delivery_eta', models.TextField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
