# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('currency_code', models.CharField(blank=True, default='SEK', max_length=100)),
                ('tracking_url', models.TextField(default='')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
