# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_delivery_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='quoteId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
