# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 14:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_delivery_quoteid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='quoteId',
            new_name='quote_id',
        ),
    ]
