# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_delivery_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='assigned_at',
            field=models.IntegerField(blank=True, default=0, editable=False),
        ),
    ]
