# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-24 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import snabb.deliveries.models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_auto_20161024_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField(default='0.0')),
                ('longitude', models.FloatField(default='0.0')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('quote_id', models.CharField(default=snabb.deliveries.models._create_hash, max_length=20, unique=True)),
                ('currency_code', models.CharField(blank=True, default='SEK', max_length=100)),
                ('pickup_eta', models.IntegerField(default=0)),
                ('delivery_eta', models.TextField(default=0)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
