# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_location_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
