# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInfo',
            fields=[
                ('appInfo_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, max_length=300, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
            ],
            options={
                'verbose_name': ('AppInfo',),
                'verbose_name_plural': 'AppsInfo',
            },
        ),
    ]
