# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinimumPrice',
            fields=[
                ('price_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], max_length=50, null=True, verbose_name='Size type')),
                ('price_value', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=50, verbose_name='Minimum Price')),
                ('price_meters', models.IntegerField(blank=True, default=0, verbose_name='Meters')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('price_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_city', to='location.City')),
            ],
            options={
                'verbose_name': 'Minimum Price',
                'verbose_name_plural': 'Minimum Prices',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('size_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('size', models.CharField(blank=True, choices=[('small', 'Small'), ('medium', 'Medium'), ('big', 'Big')], max_length=50, null=True, verbose_name='Size type')),
                ('size_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=50, verbose_name='Price/meter')),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, default=0, editable=False)),
                ('updated_at', models.IntegerField(default=0, editable=False)),
                ('size_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='City', to='location.City')),
            ],
            options={
                'verbose_name': 'Size',
                'verbose_name_plural': 'Sizes',
            },
        ),
    ]
