# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_onfleet_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Onfleet ID'),
        ),
    ]
