# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_task_task_onfleet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.CharField(editable=False, max_length=300, primary_key=True, serialize=False),
        ),
    ]
