# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_task_task_onfleet_id'),
    ]
    # We need to do all this stuff to avoid error with constraints.
    operations = [
        migrations.RunSQL(
            "ALTER TABLE quote_quote_tasks DROP CONSTRAINT quote_quote_tasks_quote_id_23b85a6d_fk_quote_quote_quote_id;"),
        migrations.RunSQL(
            "ALTER TABLE deliveries_delivery DROP CONSTRAINT deliveries_d_delivery_quote_id_67ccdcdd_fk_quote_quote_quote_id;"),
        # Add new constraint to quote_quote_tasks
        migrations.RunSQL(
            "ALTER TABLE quote_quote ALTER COLUMN quote_id TYPE varchar(300);"),
        migrations.RunSQL(
            "ALTER TABLE quote_quote_tasks ALTER COLUMN quote_id TYPE varchar(300);"),
        migrations.RunSQL(
            "ALTER TABLE quote_quote_tasks ADD CONSTRAINT quote_quote_tasks_quote_id_23b85a6d_fk_quote_quote_quote_id FOREIGN KEY (quote_id) REFERENCES quote_quote (quote_id) DEFERRABLE INITIALLY DEFERRED;"),
        # Add new constraint to deliveries_delivery
        migrations.RunSQL(
            "ALTER TABLE deliveries_delivery ALTER COLUMN delivery_quote_id TYPE varchar(300);"),
        migrations.RunSQL(
            "ALTER TABLE deliveries_delivery ADD CONSTRAINT deliveries_d_delivery_quote_id_67ccdcdd_fk_quote_quote_quote_id FOREIGN KEY (delivery_quote_id) REFERENCES quote_quote (quote_id) DEFERRABLE INITIALLY DEFERRED;")
    ]
