# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_task_task_onfleet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='quote_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
